### PR TITLE
Rename abstractions to model_builders

### PR DESCRIPTION
**Pull request by rabernat**
I find myself disliking the name `abstractions`. Everything in software is an abstraction. This is more specific.

### CODE REVIEW

**Comment by cisaacstern** [comment]
Yep, this is better!

**Comment by rabernat** [comment]
Unsure why local pre-commit is not agreeing with CI pre-commit.

**Comment by rabernat** [comment]
oops and I just accidentally pushed to main 🤦 

glad to have me working on this yet?

**Comment by cisaacstern** [comment]
> glad to have me working on this yet?

a small price to pay

**Pull request merged**
