### PR TITLE
Add dataset model

### LINKED ISSUE #20: Add database model to API
In my issue dump yesterday, I forgot perhaps the most important model of all: the datasets! 😁 

```
Table dataset {
  id int [pk]
  name varchar
  produced_by int [ref: > recipe_run.id]
  type dataset_type
  public_url varchar
 }
```

Each successful recipe run will presumably deposit a dataset somewhere. These datasets are the point of all of this work!

### PR DESCRIPTION
**Pull request by cisaacstern**
WIP

Closes #20 when complete

### CODE REVIEW

**Comment by cisaacstern** [comment]
@rabernat, a few points for you to consider in your review:

1. With the addition of `dataset` we've added the possibility of "inner" dependencies to the tests. That is, when we are creating a `dataset`, we must first create a `recipe_run`, which itself depends on `feedstock` and `bakery`. This is handled by an edit to the `create_with_dependencies` function in `test_api.py`
2. It turns out Postgres doesn't allow us to delete a table row which is currently referenced by a foreign key in another existing table. Therefore, the order in which we call `clear_table` in the tests matters. I've made a note of this at the definition of `MODELS` in `pangeo_forge_orchestrator.models`. Perhaps there's a more explicit way to handle this than just being sensitive to the ordering of `MODELS`. (Not to mention the order of that dict is not guaranteed.)
3. Note that on `dataset`, I'm calling the user-defined foreign key for the corresponding recipe run `reciperun_id`. And the automatically back-populated field (with the full details of the recipe run) is called `produced_by`. This is to keep foreign key field naming conventions consistent with `RecipeRunBase`, in which we already have `bakery_id` and `feedstock_id`.
4. **_(The most important question.)_** Is there ever a situation where a single recipe run would result in multiple datasets being produced? That is, in the case of a recipe.py defining a `dict_object`, do all of the recipes in that object get tied to a single recipe run, or does each one get it's own recipe run? From a Pydantic/SQLModel/FastAPI standpoint, it's actually much better if we can assume a possible one-to-many relationship between recipe runs and datasets, because for some reason annotating `RecipeRun.dataset` as `Optional[DatasetBase]` causes a tricky FastAPI parsing issue, whereas annotating `RecipeRun.datasets` as `List[DatasetBase]` (as I've currently done) is totally fine. If we end up wanting to use the former (one-to-one) annotation, this [discussion of idempotency issues with of FastAPI `response_models`](https://github.com/samuelcolvin/pydantic/issues/1223#issuecomment-585371034) appears relevant.

**Comment by rabernat** [comment]
Thanks for getting this started. I'd like #38 to go in first if possible.

**Review by rabernat — COMMENTED** [review]
Thanks for getting this started. I'd like #38 to go in first if possible.

**Comment by rabernat** [comment]
> With the addition of dataset we've added the possibility of "inner" dependencies to the tests. That is, when we are creating a dataset, we must first create a recipe_run, which itself depends on feedstock and bakery. This is handled by an edit to the create_with_dependencies function in test_api.py

This feels a little janky to me. I think a recursive approach would be better. Or better yet, actual fixtures. Yes, I think that's the way to go. If a particular test--e.g. dataset--needs a recipe run created first, that should be injected via a fixture. If that fixture needs a bakery, another fixture. This will likely require a significant refactor to the tests, but I think it's the only viable path forward. This is exactly what fixtures are for.

**Comment by rabernat** [comment]
> 2\. It turns out Postgres doesn't allow us to delete a table row which is currently referenced by a foreign key in another existing table. Therefore, the order in which we call `clear_table` in the tests matters. I've made a note of this at the definition of `MODELS` in `pangeo_forge_orchestrator.models`. Perhaps there's a more explicit way to handle this than just being sensitive to the ordering of `MODELS`. (Not to mention the order of that dict is not guaranteed.)

I believe the best way to handle this could be again via the fixture approach I mentioned in my previous comment. Fixtures can have teardown, e.g.

```python
@pytest.fixture
def bakery():
    # create bakery
    yield bakery
    # delete bakery when fixture is done
```

Doing things this way would completely eliminate the need to manually clear out the table each time. It would also allow us to avoid explicitly referencing foreign key ids in the fixtures. They would be determined at run time.

**Comment by rabernat** [comment]
> 4\. Is there ever a situation where a single recipe run would result in multiple datasets being produced? That is, in the case of a recipe.py defining a `dict_object`, do all of the recipes in that object get tied to a single recipe run, or does each one get its own recipe run?

In my head, one "recipe run" should be able to produce multiple datasets. But as I think deeper, that seems inconsistent with  ADR2! 🤦  I think you have exposed a problem with how we have been thinking about things that really needs to be resolved.

Really the way it works is that **one feedstock can define many recipes**, but **each recipe produces only one dataset**. 

If there is a 1:1 relationship between datasets and recipe_runs, perhaps we just want to merge them into a single table!?! 🤯 

The confounding thing is that _the action that triggers a recipe to run is an update to the feedstock repo itself_ (e.g. a commit). But we need to get comfortable with the idea that such an update may trigger multiple recipe runs.

We should talk about this face to face tomorrow. I'm free until 1pm so just ping me when you start work for the day.

**Comment by cisaacstern** [comment]
> This will likely lead to transforming the data structures in model_fixtures.py into actual fixtures. That's okay. Let's try to keep the simple, readable structure as much as we can. 

I'll confess keeping `model_fixtures.py` readable, while also using fixtures, feels mind-bending upon first/casual consideration. I imagine it is possible, but just registering the feeling, fwiw!

> If there is a 1:1 relationship between datasets and recipe_runs, perhaps we just want to merge them into a single table!?! 🤯

This is an interesting reflection which I'll look forward to discussing synchronously. There's the data model aspect (what is elegant/logical), but also the implementation aspect. Re: the latter, it does seem that a lot of the complexity we're encountering in this PR stems from the "inner" table dependencies triggered by `dataset` being its own table. Makes me wonder if combining these tables is worthwhile from a "go-to-market" timeline standpoint? Look forward to discussing.

**Comment by cisaacstern** [comment]
Per our conversation, we'll move the `dataset` fields into `reciperun` (given they are 1-to-1), and note the fixture refactors as TODOs (strategic debt in the interest of shipping!). Will reopen those items as a fresh PR.

**Pull request closed without merging**
