### PR TITLE
Add GH workflow for syncing labels across pangeo-forge organisation

### PR DESCRIPTION
**Pull request by andersy005**
~~This is still a work-in-progress PR~~

### CODE REVIEW

**Comment by andersy005** [comment]
pre-commit.ci autofix

**Comment by andersy005** [comment]
pre-commit.ci autofix

**Comment by andersy005** [comment]
@cisaacstern, this is ready for review when you get a chance

**Review by cisaacstern — COMMENTED** [review]
Thanks a lot @andersy005. This looks like a great foundation. The main gaps I see here not technical, but rather strategic. Before we merge this and start having labels synced every hour, I think we want to spend a bit more effort + time thinking about how we will use this feature to aid development. This could be brainstormed in here in the PR conversation thread, but ultimately I think should be memorialized in the developer docs here (`docs/README.md`) before merge. Some points that I find myself wondering about:

- Where will the project board live that aggregates these labels? How will we use it?
- _What_ specific labels do we want? The existing labels represent those we have reactively created over time on various repos in the org. What would it look like to deliberately design a labeling scheme, rather than just sync these existing labels across all repos?
- Continuing the theme of the previous bullet point, how can we make the `blocked:` series of labels more instructive/specific? Currently, they are very general (`recipes-feature`, etc.). How can we link them to specific issue or PR numbers?

Also, more generally, are there any examples of successful org-wide label syncing out in the world, which we could benefit from referencing?

My main concern with "merge first, refine later" for this PR (a strategy I tend to like in other circumstances), is that this PR has considerable (hourly) side effects across the entire org. So I think we will benefit from putting in the extra design thinking up front here. If this is something you're interested in thinking about, please feel free to keep going with it. I recognize it's a bit of a broader scope than we initially discussed, though, so if you'd rather leave this for someone else to pick up at a later date, IMO that's good too.

**Comment by andersy005** [comment]
Great questions, @cisaacstern 

> Where will the project board live that aggregates these labels? How will we use it?

I haven't given much thought to where the project board for aggregating the labels will live. My initial priority was to ensure the label syncing works properly before moving on to creating the project board and automating processes.

> What specific labels do we want? The existing labels represent those we have reactively created over time on various repos in the org. What would it look like to deliberately design a labeling scheme, rather than just sync these existing labels across all repos?

👍🏽 to designing a labeling scheme. however, However, I'm not sure about the upfront time commitment for this process. It may require some trial and error to determine the most effective labeling scheme, but it could ultimately lead to a more organized and efficient workflow.

> Continuing the theme of the previous bullet point, how can we make the blocked: series of labels more instructive/specific? Currently, they are very general (recipes-feature, etc.). How can we link them to specific issue or PR numbers?

In my opinion, the organization and tracking aspect of the blocked labels series can be better handled using the features of the project board. Instead of trying to make the labels too specific, we can utilize the project board to link them to specific issue or PR numbers and provide more context. This would make the tracking process more efficient and provide a clearer picture of the status of each item.


i might not have much bandwidth for this in the next few days, so anyone who's got some time should feel free to take the lead. Otherwise, I'm cool to revisit this later this week or next week

**Comment by cisaacstern** [comment]
Great insights, @andersy005.

> the organization and tracking aspect of the blocked labels series can be better handled using the features of the project board. Instead of trying to make the labels too specific, we can utilize the project board to link them to specific issue or PR numbers and provide more context

I'd love to see more on what you think this could look like in practice.

To be a bit more specific of what I'm thinking of: ideally, I think it would be great if a given recipe contributor, whose recipe contribution PR is marked `blocked:{SOMETHING}`, could use that {SOMETHING} to clearly understand what specific issue (on recipes, orchestrator, runner, etc) was blocking their PR. This way, they would have more clarity as to what's going on, and also possibly some direction as to how to help resolve the issue.

> trial and error to determine the most effective labeling scheme, but it could ultimately lead to a more organized and efficient workflow.

I am in favor of more time and effort upfront, if it can save time and effort wrangling/maintaining an under-designed approach later on.

> My initial priority was to ensure the label syncing works properly before moving on to creating the project board and automating processes.

Yes, that makes sense! In which case a follow-on question would be: how do we know that this process does works? Should we add a test under ... `.github/tests/test_label_sync.py`?

>  so anyone who's got some time should feel free to take the lead. Otherwise, I'm cool to revisit this later this week or next week

I fear that there may not be too many other people following this thread. 😆 :cavernous_echo_chamber_emoji: 😆 (But if you're out there and interested in helping, by all means chime in!) So if you're down to work on this later this week or next, I think it's all yours Anderson! Thanks again for the thoughtful contributions here.

**Pull request closed without merging**
